### ISSUE TITLE
Behavior conflicts with ESLint

### ISSUE THREAD

**Issue by aneilbaboo** [chfritz/atom-sane-indentation#11]
ESLint seems to be adding only one indent level for all open braces on a line, so reformatting with sane-indentation causes an ESLint error:

![](http://g.recordit.co/lgf7ScJzkz.gif)

**Comment by chfritz** [comment]
Yes, that behavior is preferred by many, including some of the maintainers of atom.io. However, this is not currently possible to get right, because atom.io currently uses relative indentation only, i.e., the only thing that matters to the indentation of line N is the indentation and symbols appearing on line N-1. Hence, as you can probably already see, there is no way to tell how far you need to un-indent on the closing scopes. If the opening and closing brackets are perfectly symmetric as in your example, then that could be handled by simply *not* counting the number of opening/closing scopes, and in fact that's exactly what atom.io currently natively does. But this also leads to thing like this:

```js
if (condition) {
  foo({
    option: true
  },
  callback);  // wrong indentation
foo2();  // wrong indentation 
}  // this line will even receive a negative indentation (which atom.io simply resets to 0)
```

I believe the atom.io team is planning a better indentation logic based on a parse tree of the code. Once that is done this can be accomplished. At that point, I plan to retire sane-indentation because it will hopefully no longer be required.

**Comment by aneilbaboo** [comment]
Ah, I see the difficulty.  Thank you for the detailed explanation.
